controller_manager:
  ros__parameters:
    update_rate: 1  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    joints:
      - tracking_right_pivot_joint
      - tracking_left_pivot_joint
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
