teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 2.0
    scale_linear_turbo:
      x: 1.5

    axis_angular:
      yaw: 2
    scale_angular:
      yaw: 2.0

    enable_button: 5   #L2 shoulder button
    enable_turbo_button: 4  #right button number 3
    # use_sim_time: false  (All stack is working on ros2 time, so set sim time to false)